// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hotstuff/types/message.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HsProposal struct {
	EpochView   int64        `protobuf:"varint,1,opt,name=epoch_view,json=epochView,proto3" json:"epoch_view,omitempty"`
	Block       *Block       `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	TimeoutCert *TimeoutCert `protobuf:"bytes,3,opt,name=timeout_cert,json=timeoutCert,proto3" json:"timeout_cert,omitempty"`
	Time        time.Time    `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time"`
	Signature   []byte       `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *HsProposal) Reset()         { *m = HsProposal{} }
func (m *HsProposal) String() string { return proto.CompactTextString(m) }
func (*HsProposal) ProtoMessage()    {}
func (*HsProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a3b8179c588cc87, []int{0}
}
func (m *HsProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HsProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HsProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HsProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HsProposal.Merge(m, src)
}
func (m *HsProposal) XXX_Size() int {
	return m.Size()
}
func (m *HsProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_HsProposal.DiscardUnknown(m)
}

var xxx_messageInfo_HsProposal proto.InternalMessageInfo

func (m *HsProposal) GetEpochView() int64 {
	if m != nil {
		return m.EpochView
	}
	return 0
}

func (m *HsProposal) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *HsProposal) GetTimeoutCert() *TimeoutCert {
	if m != nil {
		return m.TimeoutCert
	}
	return nil
}

func (m *HsProposal) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func (m *HsProposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type HsVote struct {
	View             int64     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	BlockID          BlockID   `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id"`
	ValidatorAddress []byte    `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	EpochView        int64     `protobuf:"varint,4,opt,name=epoch_view,json=epochView,proto3" json:"epoch_view,omitempty"`
	Time             time.Time `protobuf:"bytes,5,opt,name=time,proto3,stdtime" json:"time"`
	Signature        []byte    `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *HsVote) Reset()         { *m = HsVote{} }
func (m *HsVote) String() string { return proto.CompactTextString(m) }
func (*HsVote) ProtoMessage()    {}
func (*HsVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a3b8179c588cc87, []int{1}
}
func (m *HsVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HsVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HsVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HsVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HsVote.Merge(m, src)
}
func (m *HsVote) XXX_Size() int {
	return m.Size()
}
func (m *HsVote) XXX_DiscardUnknown() {
	xxx_messageInfo_HsVote.DiscardUnknown(m)
}

var xxx_messageInfo_HsVote proto.InternalMessageInfo

func (m *HsVote) GetView() int64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HsVote) GetBlockID() BlockID {
	if m != nil {
		return m.BlockID
	}
	return BlockID{}
}

func (m *HsVote) GetValidatorAddress() []byte {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *HsVote) GetEpochView() int64 {
	if m != nil {
		return m.EpochView
	}
	return 0
}

func (m *HsVote) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func (m *HsVote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*HsProposal)(nil), "hotstuff.types.HsProposal")
	proto.RegisterType((*HsVote)(nil), "hotstuff.types.HsVote")
}

func init() { proto.RegisterFile("hotstuff/types/message.proto", fileDescriptor_3a3b8179c588cc87) }

var fileDescriptor_3a3b8179c588cc87 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xbd, 0x6e, 0xd4, 0x40,
	0x10, 0xc7, 0xbd, 0x89, 0xef, 0x92, 0x6c, 0x4e, 0x7c, 0xac, 0x40, 0x58, 0x26, 0xd8, 0xa7, 0x54,
	0x27, 0x45, 0xb2, 0x25, 0xd2, 0x50, 0x21, 0xe1, 0x50, 0x24, 0x05, 0x12, 0xb2, 0x50, 0x0a, 0x1a,
	0xcb, 0x1f, 0x6b, 0xdf, 0x0a, 0x9b, 0xb1, 0xbc, 0xeb, 0x84, 0x3c, 0x00, 0x7d, 0x1e, 0xeb, 0xca,
	0x2b, 0xa9, 0x0e, 0xe4, 0x7b, 0x01, 0x1e, 0x01, 0x79, 0x7c, 0x1f, 0x9c, 0x05, 0x55, 0x1a, 0xcb,
	0xf3, 0xff, 0xcf, 0x5f, 0x3b, 0xf3, 0xd3, 0xd0, 0x93, 0x29, 0x28, 0xa9, 0xea, 0x34, 0x75, 0xd5,
	0x5d, 0xc9, 0xa5, 0x5b, 0x70, 0x29, 0xc3, 0x8c, 0x3b, 0x65, 0x05, 0x0a, 0xd8, 0xa3, 0xb5, 0xeb,
	0xa0, 0x6b, 0x3e, 0xcb, 0x20, 0x03, 0xb4, 0xdc, 0xf6, 0xaf, 0xeb, 0x32, 0xed, 0x0c, 0x20, 0xcb,
	0xb9, 0x8b, 0x55, 0x54, 0xa7, 0xae, 0x12, 0x05, 0x97, 0x2a, 0x2c, 0xca, 0x55, 0x83, 0xd9, 0x7b,
	0x04, 0xbf, 0xff, 0xf1, 0xa2, 0x1c, 0xe2, 0x2f, 0x9d, 0x77, 0xfa, 0x9b, 0x50, 0x7a, 0x29, 0x3f,
	0x56, 0x50, 0x82, 0x0c, 0x73, 0xf6, 0x8a, 0x52, 0x5e, 0x42, 0x3c, 0x0d, 0x6e, 0x04, 0xbf, 0x35,
	0xc8, 0x98, 0x4c, 0xf6, 0xfd, 0x23, 0x54, 0xae, 0x05, 0xbf, 0x65, 0x67, 0x74, 0x80, 0x61, 0x63,
	0x6f, 0x4c, 0x26, 0xc7, 0xaf, 0x9f, 0x3b, 0xbb, 0xc3, 0x3b, 0x5e, 0x6b, 0xfa, 0x5d, 0x0f, 0x7b,
	0x4b, 0x47, 0xed, 0x94, 0x50, 0xab, 0x20, 0xe6, 0x95, 0x32, 0xf6, 0x31, 0xf3, 0xb2, 0x9f, 0xf9,
	0xd4, 0xf5, 0x5c, 0xf0, 0x4a, 0xf9, 0xc7, 0x6a, 0x5b, 0xb0, 0x37, 0x54, 0x6f, 0x4b, 0x43, 0xc7,
	0x9c, 0xe9, 0x74, 0x08, 0x9c, 0x35, 0x02, 0x0c, 0x22, 0x02, 0xef, 0x70, 0xb6, 0xb0, 0xb5, 0xfb,
	0x9f, 0x36, 0xf1, 0x31, 0xc1, 0x4e, 0xe8, 0x91, 0x14, 0xd9, 0xd7, 0x50, 0xd5, 0x15, 0x37, 0x06,
	0x63, 0x32, 0x19, 0xf9, 0x5b, 0xe1, 0xf4, 0xfb, 0x1e, 0x1d, 0x5e, 0xca, 0x6b, 0x50, 0x9c, 0x31,
	0xaa, 0xff, 0xb5, 0x28, 0xfe, 0xb3, 0x0b, 0x7a, 0x88, 0xf3, 0x07, 0x22, 0x59, 0xad, 0xf9, 0xe2,
	0x9f, 0x6b, 0x5e, 0xbd, 0xf7, 0x1e, 0xb7, 0xef, 0x36, 0x0b, 0xfb, 0x60, 0x25, 0xf8, 0x07, 0x98,
	0xbc, 0x4a, 0xd8, 0x19, 0x7d, 0x7a, 0x13, 0xe6, 0x22, 0x09, 0x15, 0x54, 0x41, 0x98, 0x24, 0x15,
	0x97, 0x12, 0x01, 0x8c, 0xfc, 0x27, 0x1b, 0xe3, 0x5d, 0xa7, 0xf7, 0xa0, 0xeb, 0x7d, 0xe8, 0x6b,
	0x0e, 0x83, 0x87, 0x71, 0x18, 0xf6, 0x38, 0x78, 0x1f, 0x66, 0x8d, 0x45, 0xe6, 0x8d, 0x45, 0x7e,
	0x35, 0x16, 0xb9, 0x5f, 0x5a, 0xda, 0x7c, 0x69, 0x69, 0x3f, 0x96, 0x96, 0xf6, 0xf9, 0x3c, 0x13,
	0x6a, 0x5a, 0x47, 0x4e, 0x0c, 0x85, 0xfb, 0xad, 0x4e, 0xb9, 0x90, 0x90, 0xe6, 0x77, 0xee, 0xe6,
	0x8c, 0xba, 0xf3, 0xdc, 0xbd, 0xaa, 0x68, 0x88, 0xea, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x59, 0x5b, 0xb4, 0x32, 0xef, 0x02, 0x00, 0x00,
}

func (m *HsProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HsProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HsProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Time):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintMessage(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if m.TimeoutCert != nil {
		{
			size, err := m.TimeoutCert.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EpochView != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.EpochView))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HsVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HsVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HsVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Time):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintMessage(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2a
	if m.EpochView != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.EpochView))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintMessage(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.BlockID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.View != 0 {
		i = encodeVarintMessage(dAtA, i, uint64(m.View))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HsProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochView != 0 {
		n += 1 + sovMessage(uint64(m.EpochView))
	}
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.TimeoutCert != nil {
		l = m.TimeoutCert.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovMessage(uint64(l))
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *HsVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.View != 0 {
		n += 1 + sovMessage(uint64(m.View))
	}
	l = m.BlockID.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.EpochView != 0 {
		n += 1 + sovMessage(uint64(m.EpochView))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovMessage(uint64(l))
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HsProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HsProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HsProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochView", wireType)
			}
			m.EpochView = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochView |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &Block{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutCert", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TimeoutCert == nil {
				m.TimeoutCert = &TimeoutCert{}
			}
			if err := m.TimeoutCert.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HsVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HsVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HsVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field View", wireType)
			}
			m.View = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.View |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = append(m.ValidatorAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorAddress == nil {
				m.ValidatorAddress = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochView", wireType)
			}
			m.EpochView = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochView |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
